# Generated by Django 2.2 on 2019-04-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Name')),
                ('lastname', models.CharField(max_length=255)),
                ('fathername', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='workers/')),
                ('date_birn', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Position')),
            ],
            options={
                'verbose_name': 'Workers',
                'verbose_name_plural': 'Workers',
                'ordering': ['date_created'],
            },
        ),
    ]
