# Generated by Django 2.2 on 2019-04-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20190416_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
